PillsReminder/Models/Patient.cs
using System;

namespace PillsReminder.Models
{
    //public class Patient
    //{
    //    public int Id { get; set; }
    //    public string Name { get; set; }
    //    public string LastName { get; set; }
    //    public string Password { get; set; }
    //    public string Login { get; set; }
    //    public DateTime DateBorn { get; set; }
    //    public string PhoneNumber { get; set; }
    //    public Schedule Schedule { get; set; }
    //    public PatientStatus Status { get; set; }
    //}

    public enum PatientStatus
    {
        AllPillsTaken = 0,
        AcceptableMissed = 1,
        ManyMissed = 2
    }
}

PillsReminder/ViewModels/PatientViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.UI.WebControls;
using PillsReminder.Models;

namespace PillsReminder.ViewModels
{
    public class PatientViewModel
    {
        public PatientViewModel()
        {
        }

        public PatientViewModel(User patient)
        {
            Id = patient.Id;
            Name = patient.FirstName;
            LastName = patient.LastName;
            Login = patient.UserName;
            Password = patient.PasswordHash;
            DateBorn = patient.DateBorn;
            PhoneNumber = patient.PhoneNumber;
            // Schedule = patient.Schedule;
            Status = patient.Status;
        }

        public User ToDbObject()
        {
            return new User
            {
                Id = this.Id,
                FirstName = this.Name,
                LastName = this.LastName,
                UserName = this.Login,
                DateBorn = this.DateBorn,
                PhoneNumber = this.PhoneNumber,
                // Schedule = this.Schedule
                Status = Status
            };
        }

        [Required]
        public string Id { get; set; }

        [Required]
        [Display(Name = "Имя")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Login { get; set; }

        [Required]
        [Display(Name = "Пароль")]
        public string Password { get; set; }

        [Required]
        [Display(Name = "Расписание")]
        public string Schedule { get; set; }

        [Display(Name = "Дата Рождения")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateBorn { get; set; }

        [Display(Name = "Телефон")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Статус")]
        public PatientStatus Status { get; set; }
    }
}

PillsReminder/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using PillsReminder.Models;
using PillsReminder.ViewModels;
using WebGrease.Css.Extensions;

namespace PillsReminder.Controllers
{
    public class PatientsController : BaseController
    {
        private UserStore<User, AspnetRole, string, AspnetUserLogin, AspnetUserRole, AspnetUserClaim> userStore;
        private UserManager<User, string> userManager;

        public PatientsController()
        {
            userStore = new UserStore<User, AspnetRole, string, AspnetUserLogin, AspnetUserRole, AspnetUserClaim>(db);
            userManager = new UserManager<User, string>(userStore);
        }
        [Authorize(Roles = "Doctor")]
        // GET: Patients
        public async Task<ActionResult> Index()
        {
            var db_patients = await db.Users.Where(u => u.FirstName != "Doctor").ToListAsync();
            var patients = db_patients.Select(p => new PatientViewModel(p));

            return View(patients);
        }

       
        public async Task<ActionResult> GetPatientsList()
        {
            var db_patients = await db.Users.ToListAsync();
            var patients = db_patients.Select(p => new PatientViewModel(p));

            return Json(patients, JsonRequestBehavior.AllowGet);
        }

        // GET: Patients/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id.IsNullOrWhiteSpace())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User patient = await db.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(new PatientViewModel(patient));
        }

        public async Task<ActionResult> GetPatientDetails(string id)
        {
            if (id.IsNullOrWhiteSpace())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User patient = await db.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return Json(new PatientViewModel(patient), JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Authorize(string login, string password)
        {
            bool result = await db.Users.AnyAsync(p => p.UserName == login);
            return Json(new { authorized = true }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetPatientSchedule(string login, string password)
        {
            List<DateTime> times = new List<DateTime>()
            {
                new DateTime(1, 1, 1, 10, 0, 0),
                new DateTime(1, 1, 1, 12, 0, 0),
                new DateTime(1, 1, 1, 16, 30, 0),
                new DateTime(1, 1, 1, 20, 00, 0),
            };

            var items = times.Select(x => new { Time = x.ToString("HH:mm"), Description = "Показать такое сообщение" });
            return Json(items, JsonRequestBehavior.AllowGet);
        }

        // GET: Patients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PatientViewModel patient)
        {
            var db_patient = patient.ToDbObject();
           
            db_patient.Id = Guid.NewGuid().ToString();
            db_patient.Email = db_patient.UserName;
            var result = await userManager.CreateAsync(db_patient, patient.Password);
            await userManager.AddToRoleAsync(db_patient.Id, "Patient");
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: Patients/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id.IsNullOrWhiteSpace())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User patient = await db.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(new PatientViewModel(patient));
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PatientViewModel patient)
        {
           
                var db_patient = patient.ToDbObject();
                db_patient.PasswordHash = "asdasd";
                db.Entry(db_patient).State = EntityState.Modified;
                await db.SaveChangesAsync();
                await userManager.RemovePasswordAsync(db_patient.Id);
                await userManager.AddPasswordAsync(db_patient.Id, "123456");

                return RedirectToAction("Index");
            
            return View(patient);
        }

        // GET: Patients/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id.IsNullOrWhiteSpace())
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User patient = await db.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(new PatientViewModel(patient));
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            User patient = await db.Users.FirstOrDefaultAsync(u => u.Id == id);
            db.Users.Remove(patient);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public async Task<ActionResult> TakePill(string login, string password, string dateTaken)
        {
            var userEntity = await userManager.FindByNameAsync(login);
            var user = await db.Users.FirstAsync(x => x.Id == userEntity.Id);
            var result = await userManager.CheckPasswordAsync(user, password);
            if (result)
            {
                DateTime dateTakenParced = DateTime.Parse(dateTaken);
                user.PillReceivings.Add(new PillReceiving() { DateTaken = dateTakenParced });
                await db.SaveChangesAsync();
            }
            return Json(new { success = result }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Patient")]
        public async Task<ActionResult> TakePills()
        {
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Patient")]
        public async Task<ActionResult> TakeFlower()
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.First(x => x.Id == userId);
          
            user.PillReceivings.Add(new PillReceiving() { DateTaken = DateTime.Now });
            await db.SaveChangesAsync();
            
            return RedirectToAction("Index", "Home");
        }

        public async Task<ActionResult> ViewChart(string userId)
        {
            var user = db.Users.First(x => x.Id == userId);
            var takenDays = user.PillReceivings.Select(x => x.DateTaken);
            var dict = new Dictionary<string, List<string>>();
            foreach (var takenDay in takenDays)
            {
                if (!dict.ContainsKey(takenDay.ToString("yyyy-MM-dd")))
                {
                    dict[takenDay.ToString("yyyy-MM-dd")] = new List<string>
                    {
                        takenDay.ToString("hh:mm")
                    };
                }
                else
                {
                    dict[takenDay.ToString("yyyy-MM-dd")].Add(takenDay.ToString("hh:mm"));
                }
            }

            ViewBag.ChartData = JsonConvert.SerializeObject( new TakenPills
            {
                User = user.FirstName + " " + user.LastName,
                TakenDays = dict.Select(day => new Day
                {
                    Date = day.Key,
                    Times = day.Value
                }).ToList()
            });
            return View();
        }

        public async Task<ActionResult> TakenPillsList()
        {
            var list = await db.PillReceivings.ToListAsync();
            return View(list);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PillsReminder/Views/Patients/Create.cshtml
@model PillsReminder.ViewModels.PatientViewModel

@{
    ViewBag.Title = "Создать";
}
<div class="well">
    <h2>Создать запись о пациенте</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Введите информацию о пациенте</h4>
            <hr />

            <div class="form-group ">
                @Html.LabelFor(model => model.Login, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Login, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Login, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DateBorn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateBorn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateBorn, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Schedule, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Schedule, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Schedule, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Добавить" class="btn btn-raised btn-primary" />
                    <br>
                    @Html.ActionLink("Вернуться к списку пациентов", "Index")
                </div>
                <div>
                    
                </div>
            </div>
        </div>
    }

   
</div> 
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PillsReminder/Views/Patients/Delete.cshtml
@model PillsReminder.ViewModels.PatientViewModel

@{
    ViewBag.Title = "Удаление";
}
<div class="well">
    <h2>Удалить карточку пациента</h2>

    <h3>Вы уверены?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal lead">
            <dt>
                @Html.DisplayNameFor(model => model.Login)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Login)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateBorn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateBorn)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Schedule)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Schedule)
            </dd>

        </dl>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Удалить" class="btn btn-raised btn-danger" /> |
                @Html.ActionLink("Вернуться к списку пациентов", "Index", null, htmlAttributes: new { @class = "btn btn-primary" })
            </div>
    }
    </div>
</div>

PillsReminder/Views/Patients/Details.cshtml
@model PillsReminder.ViewModels.PatientViewModel

@{
    ViewBag.Title = "Пациент";
}

<h2>Пациент</h2>

<div class="row">
    <div class="well bs-component col-md-offset-3 col-md-6">
        <div>
            <h4>Пациент</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Login)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Login)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateBorn)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateBorn)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.PhoneNumber)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Schedule)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Schedule)
                </dd>

            </dl>
        </div>
    </div>
</div>

        <p>
            @Html.ActionLink("Изменить", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("К списку пациентов", "Index")
        </p>

PillsReminder/Views/Patients/Edit.cshtml
@model PillsReminder.ViewModels.PatientViewModel

@{
    ViewBag.Title = "Изменить";
}

<h2>Изменить</h2>
<div class="row">
    <div class="well bs-component col-md-offset-3 col-md-6">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Пациент: @Model.Name @Model.LastName</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateBorn, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateBorn, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateBorn, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
                    @Html.LabelFor(model => model.Schedule, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Schedule, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Schedule, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Сохранить" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>
<div>
    @Html.ActionLink("К списку пациентов", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PillsReminder/Views/Patients/Index.cshtml
@model IEnumerable<PillsReminder.ViewModels.PatientViewModel>

@{
    ViewBag.Title = "Пациенты";
}
<div class="well">
    <h2>Пациенты</h2>

    <p>
        @Html.ActionLink("Добавить", "Create", null, htmlAttributes: new { @class = "btn btn-raised btn-primary" })
    </p>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Login)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateBorn)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Schedule)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="info">
                    <td>
                        @Html.DisplayFor(modelItem => item.Login)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateBorn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Schedule)
                    </td>
                    <th>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @Html.ActionLink("Изменить", "Edit", new { id = item.Id }, new { @class = "btn btn-primary btn-sm" }) |
                        @Html.ActionLink("Подробнее", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-sm" }) |
                        @Html.ActionLink("Удалить", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-sm" })
                    </td>
                </tr>
            }
        </tbody>
</table>
</div>

PillsReminder/Views/Patients/TakePills.cshtml
@{
    ViewBag.Title = "Принять";
}

<h2>Принять</h2>


<div style="margin-bottom: 10px;height: 25px;">
    @Html.ActionLink("Принять", "TakeFlower", "Patients", null, new { @class = "btn btn-default" })
</div>

PillsReminder/Views/Patients/TakenPillsList.cshtml
@model IEnumerable<PillsReminder.Models.PillReceiving>

@{
    ViewBag.Title = "TakenPillsList";
}

<h2>TakenPillsList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateTaken)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateTaken)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

PillsReminder/Views/Patients/ViewChart.cshtml
@{
    ViewBag.Title = "ViewChart";
}

<div class="well">
    <h2>График приёма лекарств</h2>
    <canvas id="line-chart-sample" width="400" height="400"></canvas>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
    <script>
        var chartData = {
            labels: [],
            datasets: [{
                label: "My First dataset",
                fillColor: "rgba(220,220,220,0.2)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: []
            },
                {
                    label: "My Second dataset",
                    fillColor: "rgba(151,187,205,0.2)",
                    strokeColor: "rgba(151,187,205,1)",
                    pointColor: "rgba(151,187,205,1)",
                    pointStrokeColor: "#fff",
                    pointHighlightFill: "#fff",
                    pointHighlightStroke: "rgba(151,187,205,1)",
                    data: []
                }]
        };

        var jsonData =@Html.Raw(ViewBag.ChartData);

//        var jsonData = {
//            "User": "Test Patient", "TakenDays": [{"Date": "2016-03-26", "Times": ["12:00", "12:00"]},
//                {"Date": "2016-03-27", "Times": ["12:00", "12:00"]}]
//        };
//
        for (var i = 0; i < jsonData.TakenDays.length; i++) {
            var takenDay = jsonData.TakenDays[i];
            chartData.labels.push(takenDay.Date);
            for (var j=0;j<takenDay.Times.length;j++) {
                chartData.datasets[j].data.push(takenDay.Times[j].split(':')[0])
            }
        }


        window.onload = function () {

            window.PatientPills = new Chart(document.getElementById("line-chart-sample").getContext("2d")).Line(chartData, {
                responsive: true,
                scaleOverride: true,
                scaleSteps: 24,
                scaleStepWidth: 1,
                scaleStartValue: 0
            });
        }

    </script>
</div>
